/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface SafetyRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getSafetyReport"
      | "getTotalReports"
      | "owner"
      | "renounceOwnership"
      | "reportCount"
      | "reports"
      | "submitSafetyReport"
      | "transferOwnership"
      | "verifySafetyReport"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OwnershipTransferred"
      | "SafetyReportSubmitted"
      | "SafetyReportVerified"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "getSafetyReport",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalReports",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "reportCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "reports",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "submitSafetyReport",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifySafetyReport",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "getSafetyReport",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalReports",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reportCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "reports", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "submitSafetyReport",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifySafetyReport",
    data: BytesLike
  ): Result;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SafetyReportSubmittedEvent {
  export type InputTuple = [
    reportId: BigNumberish,
    reporter: AddressLike,
    reportHash: BytesLike,
    reportType: string
  ];
  export type OutputTuple = [
    reportId: bigint,
    reporter: string,
    reportHash: string,
    reportType: string
  ];
  export interface OutputObject {
    reportId: bigint;
    reporter: string;
    reportHash: string;
    reportType: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SafetyReportVerifiedEvent {
  export type InputTuple = [reportId: BigNumberish, verifier: AddressLike];
  export type OutputTuple = [reportId: bigint, verifier: string];
  export interface OutputObject {
    reportId: bigint;
    verifier: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SafetyRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): SafetyRegistry;
  waitForDeployment(): Promise<this>;

  interface: SafetyRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getSafetyReport: TypedContractMethod<
    [reportId: BigNumberish],
    [
      [string, string, bigint, string, boolean] & {
        reporter: string;
        reportHash: string;
        timestamp: bigint;
        reportType: string;
        isVerified: boolean;
      }
    ],
    "view"
  >;

  getTotalReports: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  reportCount: TypedContractMethod<[], [bigint], "view">;

  reports: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, string, boolean] & {
        reporter: string;
        reportHash: string;
        timestamp: bigint;
        reportType: string;
        isVerified: boolean;
      }
    ],
    "view"
  >;

  submitSafetyReport: TypedContractMethod<
    [reportHash: BytesLike, reportType: string],
    [bigint],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  verifySafetyReport: TypedContractMethod<
    [reportId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getSafetyReport"
  ): TypedContractMethod<
    [reportId: BigNumberish],
    [
      [string, string, bigint, string, boolean] & {
        reporter: string;
        reportHash: string;
        timestamp: bigint;
        reportType: string;
        isVerified: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTotalReports"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "reportCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "reports"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, string, boolean] & {
        reporter: string;
        reportHash: string;
        timestamp: bigint;
        reportType: string;
        isVerified: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "submitSafetyReport"
  ): TypedContractMethod<
    [reportHash: BytesLike, reportType: string],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "verifySafetyReport"
  ): TypedContractMethod<[reportId: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "SafetyReportSubmitted"
  ): TypedContractEvent<
    SafetyReportSubmittedEvent.InputTuple,
    SafetyReportSubmittedEvent.OutputTuple,
    SafetyReportSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "SafetyReportVerified"
  ): TypedContractEvent<
    SafetyReportVerifiedEvent.InputTuple,
    SafetyReportVerifiedEvent.OutputTuple,
    SafetyReportVerifiedEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "SafetyReportSubmitted(uint256,address,bytes32,string)": TypedContractEvent<
      SafetyReportSubmittedEvent.InputTuple,
      SafetyReportSubmittedEvent.OutputTuple,
      SafetyReportSubmittedEvent.OutputObject
    >;
    SafetyReportSubmitted: TypedContractEvent<
      SafetyReportSubmittedEvent.InputTuple,
      SafetyReportSubmittedEvent.OutputTuple,
      SafetyReportSubmittedEvent.OutputObject
    >;

    "SafetyReportVerified(uint256,address)": TypedContractEvent<
      SafetyReportVerifiedEvent.InputTuple,
      SafetyReportVerifiedEvent.OutputTuple,
      SafetyReportVerifiedEvent.OutputObject
    >;
    SafetyReportVerified: TypedContractEvent<
      SafetyReportVerifiedEvent.InputTuple,
      SafetyReportVerifiedEvent.OutputTuple,
      SafetyReportVerifiedEvent.OutputObject
    >;
  };
}
